jidicula/clang-format-action

entrypoint.sh

Previously, the script would only exit with a nonzero code if the last
file was formatted correctly.
This change fixes the incorrect functionality so the script exits with
a nonzero code if any of the files are formatted incorrectly.
**Additional context/notes/links**
Resolves: #1

[fix][entrypoint.sh] Fix exit status for script

---

Dockerfile
entrypoint.sh

clang-format 10.0.0 has some new rules for handling line endings more
robustly. For other new rules, see the release notes linked below.
For this implementation, clang-format 10.0.0 has a new `--dry-run` or
`-n` option to emit a warning when formatting rules are not
respected. These warnings can be escalated to errors with the
`--Werror` option which additionally returns a non-zero exit code on
formatting violations.
The Dockerfile now uses the lates Ubuntu LTS version and installs
`clang-format-10` via `apt`.
Diffs between the original and formatted source file no longer need to
be stored in memory.
The output messages emitted are no longer string literals defined in
`entrypoint.sh` and are instead the …

Issue-3: [feat][entrypoint, Dockerfile] Update to clang-format-10

---

.github/workflows/dockerimage.yml
.github/workflows/shellcheck.yml

Resolves #11
Previously used v0.1.0.
Updates action-shellcheck to use 1.0.0.
None

[feat][CI] Update action-shellcheck

---

README.md

Resolves #10
It's 2020 and we call the trunk branch `main`.
See title.
Probably lots, but not in this repo.

[docs][README] Change branch name

---

README.md
action.yml
entrypoint.sh

Resolves #18
The shellscript previously did not search all possible C files, and
did not support C++ files.
- Searches for all possible C files, both source and headers
- Searches for all possible C++ files, both source and headers
None

[feat][entrypoint] Support all C/C++ files

---

.github/workflows/dockerimage.yml
.github/workflows/shellcheck.yml
README.md
action.yml
entrypoint.sh

This release candidate adds support for this workflow to check formatting of all C and C++ source and header files. See the README for details.

Support all C and C++ files

---

README.md
action.yml
entrypoint.sh

Resolves #27
Many projects have some directories that are not compliant with the
clang-format config, so the users want to be able to select which
directories get checked.
Adds an input argument to this action defining which path to check.
None.

[feat] Allow check path selection by user 

---

Dockerfile
README.md
action.yml
entrypoint.sh

Creates a new input to the action specifying version. That input is
set as an environment variable in the action, which is read in the
Dockerfile when apt-installing `clang-format`.
Resolves: #9

feat(input): Allow user to specify clang-format version

---

README.md
action.yml
entrypoint.sh

Adds an exclude-regex input so that subdirectories and files may be
omitted from the format check.
I tested this locally by simply running the `entrypoint.sh` script with various arguments.
I'm not 100% certain that this part in the yaml file will work:
```
check-path: ${{ matrix.path['check'] }}
exclude-regex: ${{ matrix.path['exclude'] }}
```

Add exclude-regex input

---

README.md

This action is super useful and very easy to use! I had one small problem setting it up though.
I tried copy/pasting one of the examples from the readme but got an error about `PR` not being a valid event name. 
I checked the [GitHub Action reference][1] and it looks like the event name should be `pull_request`.
Hopefully I am not missing anything. Thanks again for building this great action.
[1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows

Change triggering event from PR to pull_request

---

README.md
action.yml
entrypoint.sh
test/known_fail/addition.proto
test/known_pass/addition.proto

This adds support for protobuf files extensions `.proto`.
Used here: https://github.com/helium/proto

Add support for proto/pb files

---

Dockerfile

Ubuntu Groovy is EOL and the package repos don't seem to be available anymore
Fixes #62
---
Ubuntu 20.04 supports clang-format up to version 12 it seems. Not sure if Groovy used to supported more versions.

chore: switch to ubuntu 20.04

---

entrypoint.sh

This find command seems to work from my bare-bones testing in a personal project. Let's see if it holds up in the context of this action
Closes #66
This PR adds a seperate condition to the find command that, to the best of my understanding, filters out the .git directory and it's contents to the left side of that `-o` (or) and adding the `-print` to the right side (the original query) makes it only print the results of that and not the .git directory matched by the left side.
(Not an expert with find - I just looked stuff up and read a bit in the documentation)

Attempt to fix internal git files being detected by find

---

entrypoint.sh

fix: Ignore .git files from C/C++ file suffix in branchname

---

.github/workflows/clang-format-image.yml
clang-format-docker/Dockerfile

This fetches `clang-format` binaries in LLVM versions with associated
GitHub releases. For older versions, `clang-format` is built from
source where possible to use the Makefile target for `clang-format`.
Note that this pulls down the latest patch version for this Action's
supported major versions and tags the image with the major version
only.
Part of a refactor of this action to a composite action.

feat(clang-format): Add workflow for Docker image build and push

---

clang-format-docker/Dockerfile

Might be relying on some linked libs to work.

fix(clang-format-docker): Use bullseye-slim

---

.github/workflows/clang-format-image.yml
clang-format-docker/Dockerfile

`clang-format` is not a statically linked binary, so we need to copy
in all the shared libs and other binaries so it can work properly.

fix(clang-format-docker): Include binary directory in Docker image

---

.github/workflows/clang-format-image.yml
clang-format-docker/Dockerfile

Also inject Ubuntu version and `clang-format` version as build args,
and move install operation into image build.
Related to: #33

feat(clang-format docker): Use Ubuntu as base image

---

action.yml

Arguments would get expanded before being passed to bash, which would cause the following configuration to fail:
```yaml
clang-format-version: 12
check-path: '.'
exclude-regex: '(foo|bar)'
```
because `check.sh` would get run as:
```bash
check.sh 12 . LLVM (foo|bar)
```
And since '(' and '|' are special characters for bash, the action will immediately fail because of a syntax error.
Instead, it should get ran as:
```bash
check.sh "12" "." "LLVM" "(foo|bar)"
```
This should also ensure that `check-path` works with paths containing spaces.

Quote arguments to check.sh

---

.github/workflows/clang-format-image.yml

Ubuntu Impish seems to be unsupported now and its Release files seem
to have been removed from the Ubuntu repositories.
> #6 1.390 E: The repository 'http://security.ubuntu.com/ubuntu impish-security Release' does not have a Release file.
See failures in https://github.com/jidicula/clang-format-action/runs/7485540299?check_suite_focus=true

feat(ubuntu): Retire impish images

---

.pre-commit-config.yaml
action.yml
check.sh

Collects names of failing files and writes them to the job summary.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

Write output to workflow job summary

---

.github/workflows/test-ubuntu-18.04.yml
.github/workflows/test-ubuntu-20.04.yml
.github/workflows/test-ubuntu-22.04.yml
.github/workflows/tests.yml
README.md

Factors out runner OS into separate workflows that each call a shared
test matrix workflow. This allows CI status badges for each runner OS,
rather than a single status badge for all OSes.
Having a CI status badge for each supported runner OS allows
at-a-glance judgement of this Action's maintenance status.
Resolves: #106

ci(runner): Run tests on specific Ubuntu versions

---

check.sh

Without --rm option, it leaves a lot of stopped containers for a big project.

Automatically remove the container when it exits

---

.github/workflows/clang-format-image.yml

Note that clang-format-15 is only available in Ubuntu 22.10, Kinetic Kudu, which is still in beta at the time of this commit.
Related to: #112

feat(version): Add clang-format-15

---

.github/workflows/tests.yml
README.md

Note that clang-format-15 is only available in Ubuntu 22.10, Kinetic Kudu, which is still in beta at the time of this commit.
Resolves: #112

feat(version): Add clang-format-15 to Action

---

README.md

Update to use [`actions/checkout@v3`](https://github.com/actions/checkout)
Resolves #116

Update to checkout V3

---

README.md
check.sh
test/known_fail/addition.cu
test/known_pass/addition.cu

This is mostly a workaround for using this Action with my code until #79 is resolved.

Add support for formatting `.cu` CUDA source files

---

check.sh
test/known_pass/folder/with spaces/addition.cpp

* Adds a directory name with spaces, as a failure case to expose #130

Handles folders with spaces

---

action.yml

Instead of hardcoding the GitHub URL, instead pull in the server URL from the `github` object.

Use `github.server_url` property

---

.github/workflows/clang-format-image.yml

Hi @jidicula,
As you requested in the Pull Request #163, I am creating this PR dedicated to the new entry in the package registry :wink:

feat: Add clang-format-17 to package registry

---

.github/workflows/clang-format-image.yml
.github/workflows/tests.yml
README.md

Hi @jidicula,
I am creating this Pull Request in relation with the issue #162 :slightly_smiling_face:  (and in the context of Hacktoberfest 2023). 
I've inspired myself a lot from the Pull Requests you have linked in the issue description.
Currently, I am trying to run the script `test/test.sh` like you mentioned in the [CONTRIBUTING](https://github.com/jidicula/clang-format-action/blob/main/CONTRIBUTING.md), but I am currently having the following error:
```
Unable to find image 'ghcr.io/jidicula/clang-format:17' locally
``` 
and,
```shell
$ docker pull ghcr.io/jidicula/clang-format:17
Error response from daemon: manifest unknown
```
Maybe GitHub Actions will have the right setup, and not have this issue.
Until GitHub Actions gives me some results, I'll continue seeing if I can solve …

Add support for clang-format-17

---

.github/workflows/clang-format-image.yml

issue: #165
For ubuntu versions 13-16 switched the version to mantic in the .github\workflows\clang-format-image.yml
closes #165

refactor: Switch Ubuntu version to mantic
